// launchd wrapper, systemd unit/timer, nginx vhost generation. These are
// generated fully working (or as close as the archetype allows). The wrapper
// sources radar-kit's scripts/agent-run.sh for the shared plumbing, the same
// as every existing radar's since 2026-09-28.

export function buildWrapperSh(opts) {
  const { name, archetype } = opts
  const isServer = archetype === "server"
  return `#!/bin/bash
# Run wrapper for ${name}, called by ${name}.service (systemd on the Pi; the
# launchd/ directory name is fleet convention). Generated by radar-kit/forge.
#
# Why a wrapper at all: \`opencode run\` doesn't resolve custom slash commands
# (upstream bug), so the model and prompt are read out of
# .opencode/commands/${name}.md here and passed directly.
#
# The shared plumbing (PATH, git pull, command parsing, cost logging, the
# timeout, the completion guards, the heartbeat pi-ops reads) comes from
# radar-kit's scripts/agent-run.sh; keep only what's specific to ${name} here.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
. "$REPO_DIR/.opencode/node_modules/radar-kit/scripts/agent-run.sh" \\
  || { echo "${name}: radar-kit's scripts/agent-run.sh is missing -- run pi-ops/update-radar-kit.sh" >&2; exit 1; }

rk_init ${name}
# Built-in Exa web search/fetch. TODO: remove if this radar's prompt doesn't
# search the web (a pure computation/report radar wouldn't need it).
export OPENCODE_ENABLE_EXA=true
rk_pull
rk_load_command "$REPO_DIR/.opencode/commands/${name}.md"
${
  isServer
    ? `
# The silent-stall guard: record_outcome writes this as the run's last step,
# on both clean paths and never on an aborted one.
OUTCOME_FILE="$REPO_DIR/logs/run-outcome.json"
rm -f "$OUTCOME_FILE"

rk_cost_begin
# TODO: tune the timeout to this radar's real workload (30-45m is the fleet's usual range).
rk_run_opencode 45m "$MODEL" "$PROMPT"
rk_fail_unless_exists "$OUTCOME_FILE" \\
  "logs/run-outcome.json was not written -- the model never called record_outcome, so the run stopped before finishing."`
    : `
# TODO if this radar needs date math the model shouldn't do itself (see
# prize-radar's NEXT_CHECK), append it to $PROMPT here rather than trusting the
# model's arithmetic for anything a downstream write validates exactly.

# Completion guard for a board agent: its write tool rewrites data/state.json
# with a fresh generatedAt, so an unchanged one means the run didn't finish.
STATE_FILE="$REPO_DIR/data/state.json"
GEN_BEFORE=$(rk_json_field "$STATE_FILE" generatedAt)

rk_cost_begin
# TODO: tune the timeout to this radar's real workload (30-45m is the fleet's usual range).
rk_run_opencode 45m "$MODEL" "$PROMPT"
GEN_AFTER=$(rk_json_field "$STATE_FILE" generatedAt)
rk_fail_if_unchanged "$GEN_BEFORE" "$GEN_AFTER" \\
  "data/state.json was not rewritten (generatedAt unchanged) -- the run did not complete."

# TODO if this board radar needs to commit+push data/ itself (prize-radar's
# shape), do it here, best-effort: log a push failure, don't fail the run.`
}
rk_cost_record
rk_heartbeat
exit "$EXIT_CODE"
`
}

export function buildSystemdService(opts) {
  const { name, description } = opts
  return `[Unit]
Description=${name}${description ? " — " + description : ""}
After=network-online.target
Wants=network-online.target
OnFailure=agent-alert@%n.service

[Service]
Type=oneshot
User=mcmar
WorkingDirectory=/home/mcmar/Projects/${name}
ExecStart=/home/mcmar/Projects/${name}/launchd/run-${name}-opencode.sh
StandardOutput=append:/home/mcmar/Projects/${name}/logs/${name}.out.log
StandardError=append:/home/mcmar/Projects/${name}/logs/${name}.err.log
`
}

export function buildSystemdTimer(opts) {
  const { name, onCalendar, cadenceNote } = opts
  return `[Unit]
Description=Run ${name}'s scheduled pass

[Timer]
# TODO: confirm this slot doesn't collide with another radar's timer — check every
# OnCalendar= line already in pi-ops/systemd/*.timer before deploying.
# ${cadenceNote}
OnCalendar=${onCalendar}
Persistent=true

[Install]
WantedBy=timers.target
`
}

export function buildNginx(opts) {
  const { name, archetype, port, serverPort } = opts
  const isServer = archetype === "server"
  // Fleet convention (confirmed against serendipity-radar: nginx 8024 / server 8025, and
  // research-desk: nginx 8022 / server 8023): nginx listens on the board port, the backend
  // interest-server runs one port above it.
  return `# Serves ${name}'s static index.html${
    isServer ? " + data/" + opts.camel + ".json" : " + data/{state,digest}.json"
  } directly out of the
# repo's own working copy on this Pi. TODO: confirm the listen port below doesn't collide
# with an existing vhost (check pi-bootstrap/nginx/* for every port already in use).
server {
    listen ${port};
    listen [::]:${port};

    root /home/mcmar/Projects/${name};
    index index.html;

    location ~ /\\. {
        deny all;
    }
${
  isServer
    ? `
    location /api/ {
        proxy_pass http://127.0.0.1:${serverPort}/api/;
        proxy_set_header Host $host;
    }
`
    : ""
}}
`
}
