// launchd wrapper, systemd unit/timer, nginx vhost generation. These are
// generated fully working (or as close as the archetype allows) — the
// wrapper shape and the unit files are the most mechanically identical
// part of every radar in the fleet, confirmed by reading serendipity-radar's
// and prize-radar's real ones side by side.

export function buildWrapperSh(opts) {
  const { name, archetype } = opts
  const isServer = archetype === "server"
  return `#!/bin/bash
# Wrapper for the scheduler (systemd on the Pi; a manual terminal run on either machine).
# Generated by radar-kit/forge, mirroring ${
    isServer ? "serendipity-radar" : "prize-radar"
  }/launchd/run-${
    isServer ? "serendipity-radar" : "prize-radar"
  }-opencode.sh's shape. \`opencode run\` can't just be handed "/${name}" (upstream bug,
# opencode <1.19: the slash command isn't resolved, the literal string is forwarded to the
# model) — this pulls model + prompt body out of the command file's frontmatter itself and
# passes them via -m/argv.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
COMMAND_FILE="$REPO_DIR/.opencode/commands/${name}.md"
${isServer ? `OUTCOME_FILE="$REPO_DIR/logs/run-outcome.json"` : `STATE_FILE="$REPO_DIR/data/state.json"`}

export PATH="$HOME/.opencode/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:$PATH"
OPENCODE_BIN="$(command -v opencode || echo "$HOME/.opencode/bin/opencode")"

# Built-in Exa web search/fetch — TODO: remove this export if this radar's prompt doesn't
# search the web (a pure computation/report radar wouldn't need it).
export OPENCODE_ENABLE_EXA=true

cd "$REPO_DIR"

# This repo is the sync channel between edits made on the Mac and execution on the Pi.
git pull --ff-only origin main

MODEL=$(sed -n 's/^model: *//p' "$COMMAND_FILE" | head -1)
PROMPT=$(awk 'c>=2; /^---$/{c++}' "$COMMAND_FILE")

if [ -z "$MODEL" ] || [ -z "$PROMPT" ]; then
  echo "Failed to extract model/prompt from $COMMAND_FILE -- aborting." >&2
  exit 1
fi

export DIGEST_MODEL="$MODEL"

${
  isServer
    ? `# record_outcome writes this on the way out of every run that reaches a real
# conclusion. Clear any stale copy now so the post-run check below is a plain
# "did this run produce one" test.
mkdir -p "$REPO_DIR/logs"
rm -f "$OUTCOME_FILE"`
    : `# TODO if this archetype needs date math the model shouldn't do itself (see
# prize-radar's NEXT_CHECK) -- inject it into $PROMPT here, the same way, rather than
# trusting the model's own arithmetic for anything a downstream file-write validates
# exactly.

# Snapshot generatedAt before the run so the completion guard below can tell whether the
# write tool actually ran (opencode exits 0 even when the model abandons a run partway
# through with no error -- the fleet-wide A6 pattern).
GEN_BEFORE=$(node -e 'try{process.stdout.write(String(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).generatedAt||""))}catch{}' "$STATE_FILE" 2>/dev/null || true)`
}

# Per-run cost onto logs/digest-runs.json, same as every other agent in the fleet.
RADAR_KIT_DIR="$REPO_DIR/.opencode/node_modules/radar-kit"
RUNS_FILE="$REPO_DIR/logs/digest-runs.json"
RUN_START=$(date -u +%Y-%m-%dT%H:%M:%S)
USAGE_BEFORE=""
if [ -f "$RADAR_KIT_DIR/scripts/run-cost.js" ]; then
  USAGE_BEFORE=$(node "$RADAR_KIT_DIR/scripts/run-cost.js" read 2>/dev/null || true)
fi

# TODO: tune the timeout to this radar's real workload (30-45m is the fleet's usual range).
TIMEOUT_BIN="$(command -v timeout || true)"
RUN_CMD=("$OPENCODE_BIN" run -m "$MODEL" --auto "$PROMPT")
if [ -n "$TIMEOUT_BIN" ]; then
  RUN_CMD=("$TIMEOUT_BIN" --kill-after=2m 45m "\${RUN_CMD[@]}")
fi

if "\${RUN_CMD[@]}"; then
  EXIT_CODE=0
  STATUS="success"
else
  EXIT_CODE=$?
  STATUS="failure"
  if [ "$EXIT_CODE" -eq 124 ]; then
    echo "${name}: opencode run exceeded the timeout and was killed -- treating as a hung run." >&2
    STATUS="timeout"
  fi
fi

${
  isServer
    ? `# opencode run\` exits 0 even when the model abandons a run partway through without
# raising an error. This repo relies on record_outcome, called as the final action of
# BOTH clean paths and never on an aborted one -- see .opencode/plugins/${name}-tools.js.
if [ "$EXIT_CODE" -eq 0 ] && [ ! -e "$OUTCOME_FILE" ]; then
  echo "${name}: opencode exited 0 but logs/run-outcome.json was not written -- the model" \\
    "never called record_outcome, so the run stopped before finishing. Treating as failed." >&2
  EXIT_CODE=1
  STATUS="incomplete"
fi`
    : `if [ "$EXIT_CODE" -eq 0 ]; then
  GEN_AFTER=$(node -e 'try{process.stdout.write(String(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).generatedAt||""))}catch{}' "$STATE_FILE" 2>/dev/null || true)
  if [ -z "$GEN_AFTER" ] || [ "$GEN_AFTER" = "$GEN_BEFORE" ]; then
    echo "${name}: opencode exited 0 but data/state.json was not rewritten (generatedAt" \\
      "unchanged) -- the run did not complete." >&2
    EXIT_CODE=1
    STATUS="incomplete"
  fi
fi`
}

mkdir -p "$REPO_DIR/logs"

if [ -n "$USAGE_BEFORE" ] && [ -f "$RADAR_KIT_DIR/scripts/run-cost.js" ]; then
  node "$RADAR_KIT_DIR/scripts/run-cost.js" record "$RUNS_FILE" "$USAGE_BEFORE" "$RUN_START" || true
fi

${
  !isServer
    ? `# TODO if this radar has a static-board-only posture and needs to commit+push data/
# itself (prize-radar's shape) -- add \`git add data/*.json && git commit -m "..." && git
# push\` here, best-effort (log, don't fail the run on a push failure).

`
    : ""
}printf '{"timestamp": "%s", "exit_code": %s, "status": "%s"}\\n' \\
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$EXIT_CODE" "$STATUS" \\
  > "$REPO_DIR/logs/last-run.json"

exit "$EXIT_CODE"
`
}

export function buildSystemdService(opts) {
  const { name, description } = opts
  return `[Unit]
Description=${name}${description ? " — " + description : ""}
After=network-online.target
Wants=network-online.target
OnFailure=agent-alert@%n.service

[Service]
Type=oneshot
User=mcmar
WorkingDirectory=/home/mcmar/Projects/${name}
ExecStart=/home/mcmar/Projects/${name}/launchd/run-${name}-opencode.sh
StandardOutput=append:/home/mcmar/Projects/${name}/logs/${name}.out.log
StandardError=append:/home/mcmar/Projects/${name}/logs/${name}.err.log
`
}

export function buildSystemdTimer(opts) {
  const { name, onCalendar, cadenceNote } = opts
  return `[Unit]
Description=Run ${name}'s scheduled pass

[Timer]
# TODO: confirm this slot doesn't collide with another radar's timer — check every
# OnCalendar= line already in pi-ops/systemd/*.timer before deploying.
# ${cadenceNote}
OnCalendar=${onCalendar}
Persistent=true

[Install]
WantedBy=timers.target
`
}

export function buildNginx(opts) {
  const { name, archetype, port, serverPort } = opts
  const isServer = archetype === "server"
  // Fleet convention (confirmed against serendipity-radar: nginx 8024 / server 8025, and
  // research-desk: nginx 8022 / server 8023): nginx listens on the board port, the backend
  // interest-server runs one port above it.
  return `# Serves ${name}'s static index.html${
    isServer ? " + data/" + opts.camel + ".json" : " + data/{state,digest}.json"
  } directly out of the
# repo's own working copy on this Pi. TODO: confirm the listen port below doesn't collide
# with an existing vhost (check pi-bootstrap/nginx/* for every port already in use).
server {
    listen ${port};
    listen [::]:${port};

    root /home/mcmar/Projects/${name};
    index index.html;

    location ~ /\\. {
        deny all;
    }
${
  isServer
    ? `
    location /api/ {
        proxy_pass http://127.0.0.1:${serverPort}/api/;
        proxy_set_header Host $host;
    }
`
    : ""
}}
`
}
