// .opencode/commands/<name>.md and .opencode/plugins/<name>-tools.js generation.

export function buildCommandMd(opts) {
  const { name, description, model, isServer } = opts
  return [
    "---",
    `description: TODO — one line: what this radar searches for and how often`,
    `model: ${model}`,
    "---",
    "",
    "You are running unattended, on a schedule. TODO — replace this whole prompt with the real",
    `instructions for ${name}. This is a scaffold, not a working prompt: see the sibling radars`,
    "(`serendipity-radar/.opencode/commands/serendipity-radar.md`,",
    "`prize-radar/.opencode/commands/prize-radar.md`) for two real, working examples of this",
    "document's shape before writing your own from scratch.",
    "",
    "## What to read first",
    "",
    "TODO — list, in order, every file/tool this run should consult before acting: prior state",
    "(so it doesn't repeat itself), any sibling repo's data this radar should stay adjacent to or",
    "exclude, and `read_calibration` for past marks.",
    "",
    "## " + (isServer ? "Searching / deciding" : "Checking"),
    "",
    "TODO — the actual judgment this run performs.",
    "",
    "## Finishing",
    "",
    isServer
      ? [
          `- If you found something worth recording: call the write tool once with everything this`,
          "  run produced, then call `record_outcome` with `sent: true, count: <n>`.",
          "- If nothing this run clears the bar: do NOT call the write tool. Call `record_outcome`",
          "  with `sent: false, count: 0` and a one-line `note` on why — a quiet run is a correct",
          "  outcome, never pad to reach a number.",
          "- `record_outcome` MUST be your final action on both paths, and MUST NOT be called if",
          "  you are stopping early because a step failed — an uncalled `record_outcome` is exactly",
          "  how the scheduler detects an abandoned run.",
        ].join("\n")
      : [
          "- Call the write tool exactly once, near the end of the run, with EVERY tracked record",
          "  (not just the ones that changed — an item left out silently drops from the board).",
          '  It recomputes "changed" itself; do not try to self-report a changed flag.',
          "- TODO — decide this archetype's completion-guard contract: does it need",
          "  `record_outcome`, or (like prize-radar) does the wrapper instead confirm the state",
          "  file's `generatedAt` actually advanced? Either is fine; pick one and document it in",
          "  CLAUDE.md, because the wrapper script's guard depends on which you choose.",
        ].join("\n"),
    "",
  ].join("\n")
}

export function buildPluginToolsJs(opts) {
  const { name, camel, pascal, serverPort, archetype } = opts
  const isServer = archetype === "server"

  if (isServer) {
    return `// Custom tools for the ${name} run. Generated by radar-kit/forge — the mechanical
// plumbing (calibration, the write call, the silent-stall guard) is wired and working;
// the write tool's argument schema and the prompt driving it are TODOs.

import { tool } from "@opencode-ai/plugin/tool"
import { createCalibrationTool, createRecordOutcomeTool } from "radar-kit"

import { KEY_FIELDS } from "../../src/${camel}Key.js"

const PORT = process.env.${pascal.toUpperCase()}_PORT || "${serverPort}"

export const ${pascal}Tools = async () => {
  return {
    tool: {
      // Same key the server's mark routes write with (src/${camel}Key.js). Reads
      // data/${camel}.json directly (keep it a flat array — see src/${camel}Store.js's
      // header comment) joined against interested.json / ignored.json.
      read_calibration: createCalibrationTool({
        seenFileName: "data/${camel}.json",
        keyFields: KEY_FIELDS,
        // TODO: describe(record) — one line per record for the calibration prompt block.
        describe: (r) => JSON.stringify(r),
      }),

      // TODO: rename this tool and fill in its real argument schema (tool.schema.object(...)
      // per field) — this scaffold only proves the plumbing end to end.
      write_${camel}: tool({
        description:
          "TODO — describe what this call records and its argument shape, e.g. what fields " +
          "every record needs, how many per run, what happens on a duplicate.",
        args: {
          records: tool.schema.array(tool.schema.object({}).passthrough()),
        },
        execute: async ({ records }) => {
          const res = await fetch(\`http://127.0.0.1:\${PORT}/api/${camel}\`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ records }),
          })
          const text = await res.text()
          if (!res.ok) {
            throw new Error(\`${name} server rejected the batch (\${res.status}): \${text}\`)
          }
          return \`Recorded: \${text}\`
        },
      }),

      // Closes the silent-stall gap: opencode exits 0 even when the model abandons the run
      // before the write tool is ever reached. MUST be the last thing every completed run
      // does — on both the "wrote something" and "correctly found nothing" paths — and MUST
      // NOT be called on an aborted one. See launchd/run-${name}-opencode.sh's completion guard.
      record_outcome: createRecordOutcomeTool({
        description:
          "Record that this run reached a definite conclusion. Call exactly once, as the " +
          "very last action, on BOTH clean paths. Do NOT call it if you are stopping early " +
          "because a step failed.",
      }),
    },
  }
}
`
  }

  return `// Custom tools for the ${name} run. Generated by radar-kit/forge in the static-board
// shape (mirrors prize-radar/skyline-radar): a read-only preview tool plus the single
// writer, no server. TODO: fill in the real record schema and the classify/join logic in
// src/${camel}Store.js — this scaffold only proves the plumbing end to end.

import path from "node:path"
import { readFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"

import { tool } from "@opencode-ai/plugin/tool"
import { writeFileAtomic } from "radar-kit/atomicWrite"

import { classifyChange, buildStateFile, buildDigestFile } from "../../src/${camel}Store.js"

const REPO_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..")
const STATE_PATH = path.join(REPO_DIR, "data", "state.json")
const DIGEST_PATH = path.join(REPO_DIR, "data", "digest.json")

async function readJson(filePath, fallback) {
  try {
    return JSON.parse(await readFile(filePath, "utf8"))
  } catch {
    return fallback
  }
}

const recordSchema = tool.schema.object({}).passthrough() // TODO: real fields

export const ${pascal}Tools = async () => {
  return {
    tool: {
      // Read-only preview — call after researching, to see what actually changed before
      // writing any "this run's movement" prose. Does not persist anything.
      diff_${camel}: tool({
        description:
          "Preview which of the proposed records actually changed against data/state.json, " +
          "BEFORE writing anything. Does not persist. Call write_${camel} afterward regardless.",
        args: { records: tool.schema.array(recordSchema) },
        execute: async ({ records }) => {
          const prior = await readJson(STATE_PATH, { records: [] })
          const priorByKey = new Map((prior.records ?? []).map((r) => [JSON.stringify(r), r]))
          // TODO: key this by src/${camel}Key.js's keyOf, not JSON.stringify — this scaffold
          // keeps it dependency-free of the model's own record shape until that's decided.
          const results = records.map((next) => {
            const { changed, changeTag } = classifyChange(null, next)
            return { changed, changeTag }
          })
          return JSON.stringify({ results }, null, 2)
        },
      }),

      // The only writer. Re-runs the classification itself rather than trusting anything
      // the model reports about what changed.
      write_${camel}: tool({
        description:
          "Persist this run's results: data/state.json (every tracked record) and " +
          "data/digest.json (this run's headline/dek/movements/nextCheck). Call exactly " +
          "once, near the end of the run, with EVERY tracked record — one left out is still " +
          "carried forward from the prior run, but only researching a subset defeats the " +
          "point of a scheduled check.",
        args: {
          records: tool.schema.array(recordSchema),
          headline: tool.schema.string(),
          dek: tool.schema.string(),
          movements: tool.schema.array(tool.schema.object({}).passthrough()).optional(),
          nextCheck: tool.schema.string(),
        },
        execute: async ({ records, headline, dek, movements = [], nextCheck }) => {
          const prior = await readJson(STATE_PATH, { records: [] })
          const stateFile = buildStateFile({ priorRecords: prior.records ?? [], proposed: records })
          const digestFile = buildDigestFile({ headline, dek, movements, nextCheck })

          await writeFileAtomic(STATE_PATH, JSON.stringify(stateFile, null, 2) + "\\n", { ensureDir: true })
          await writeFileAtomic(DIGEST_PATH, JSON.stringify(digestFile, null, 2) + "\\n", { ensureDir: true })

          return JSON.stringify(
            {
              written: ["data/state.json", "data/digest.json"],
              recordCount: stateFile.records.length,
              generatedAt: stateFile.generatedAt,
            },
            null,
            2
          )
        },
      }),
    },
  }
}
`
}
