// server/server.js and index.html generation. server.js is generated fully
// working — it's pure radar-kit plumbing, the one part of the server
// archetype that genuinely doesn't vary between radars.

export function buildServerJs(opts) {
  const { name, camel, pascal, serverPort } = opts
  return `// The always-on write endpoint for ${name}. Generated by radar-kit/forge — this file
// is pure radar-kit plumbing and should not need hand-editing beyond the one route marked
// TODO below. It is the single writer of data/${camel}.json — keep it a flat array (see
// src/${camel}Store.js's header comment) — and every mutation goes through the routes
// below, serialized through withStore so two requests can't read-modify-write over each
// other. Mirrors serendipity-radar/server/server.js and research-desk/server/server.js.

import path from "node:path"
import { fileURLToPath } from "node:url"
import { readFile } from "node:fs/promises"

import { createInterestServer, sendJson } from "radar-kit/server"
import { createMarkStore } from "radar-kit/markStore"
import { createOneClickMarkRoute } from "radar-kit/oneClickMark"
import { createReviewedRoute } from "radar-kit/reviewedRoute"
import { createHealthRoute } from "radar-kit/health"
import { writeFileAtomic } from "radar-kit/atomicWrite"

import { keyOf, KEY_FIELDS } from "../src/${camel}Key.js"
import { addBatch, markDelivered, normalizeStore, emptyStore, ${pascal}Error } from "../src/${camel}Store.js"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_DIR = path.join(__dirname, "..")
const STORE_FILE = path.join(REPO_DIR, "data", "${camel}.json")
const PORT = parseInt(process.env.PORT || "${serverPort}", 10)

const marks = createMarkStore({
  paths: {
    interested: path.join(REPO_DIR, "interested.json"),
    ignored: path.join(REPO_DIR, "ignored.json"),
  },
  exclusive: true,
})

const reviewed = createMarkStore({
  paths: { reviewed: path.join(REPO_DIR, "reviewed.json") },
})

async function readStore() {
  try {
    return normalizeStore(JSON.parse(await readFile(STORE_FILE, "utf8")))
  } catch (err) {
    if (err.code === "ENOENT") return emptyStore()
    console.error("${name}: store unreadable, starting empty:", err.message)
    return emptyStore()
  }
}

// Serialize every read-modify-write, same shape as serendipity-radar's withDiscoveries /
// research-desk's withDesk.
let chain = Promise.resolve()
function withStore(mutate) {
  const run = chain.then(async () => {
    const records = await readStore()
    const result = await mutate(records)
    if (result && result.records) {
      await writeFileAtomic(STORE_FILE, JSON.stringify(result.records, null, 2) + "\\n", {
        ensureDir: true,
      })
    }
    return result
  })
  chain = run.then(
    () => {},
    () => {}
  )
  return run
}

const routes = [
  createHealthRoute({ name: "${name} server" }),

  createOneClickMarkRoute({ marks, fields: KEY_FIELDS, keyOf }),

  createReviewedRoute({ reviewed, fields: KEY_FIELDS, keyOf }),

  {
    method: "POST",
    path: "/api/interested",
    body: true,
    handler: async ({ res, body }) => {
      const value = body.interested
      if (typeof value !== "boolean") {
        return sendJson(res, 400, { error: "expected { ...KEY_FIELDS, interested: boolean }" })
      }
      const via = typeof body.via === "string" && body.via ? body.via : "web"
      await marks.set({ store: "interested", key: keyOf(body), value, via })
      sendJson(res, 200, { ok: true, interested: value })
    },
  },
  {
    method: "POST",
    path: "/api/ignored",
    body: true,
    handler: async ({ res, body }) => {
      const value = body.ignored
      if (typeof value !== "boolean") {
        return sendJson(res, 400, { error: "expected { ...KEY_FIELDS, ignored: boolean }" })
      }
      const via = typeof body.via === "string" && body.via ? body.via : "web"
      await marks.set({ store: "ignored", key: keyOf(body), value, via })
      sendJson(res, 200, { ok: true, ignored: value })
    },
  },

  // TODO: rename to match the write tool in .opencode/plugins/${name}-tools.js.
  {
    method: "POST",
    path: "/api/${camel}",
    body: true,
    handler: async ({ res, body }) => {
      try {
        const { batchId, added, skipped } = await withStore((records) => addBatch(records, body?.records))
        sendJson(res, 201, { batchId, added, skipped })
      } catch (err) {
        if (err instanceof ${pascal}Error) return sendJson(res, err.statusCode, { error: err.message })
        throw err
      }
    },
  },
  {
    method: "POST",
    path: "/api/delivered",
    body: true,
    handler: async ({ res, body }) => {
      try {
        const { count } = await withStore((records) => markDelivered(records, body?.batchId))
        sendJson(res, 200, { batchId: body?.batchId, deliveredCount: count })
      } catch (err) {
        if (err instanceof ${pascal}Error) return sendJson(res, err.statusCode, { error: err.message })
        throw err
      }
    },
  },

  {
    method: "GET",
    path: "/api/items",
    handler: async ({ res }) => {
      const records = await readStore()
      sendJson(res, 200, records)
    },
  },
]

createInterestServer({ name: "${name} server", port: PORT, routes }).listen()
`
}

export function buildIndexHtml(opts) {
  const { name, archetype, port } = opts
  const isServer = archetype === "server"
  const dataUrl = isServer ? "./data/" + opts.camel + ".json" : "./data/state.json"
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${name}</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 -apple-system, system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; }
  h1 { font-size: 1.1rem; }
  .item { border-bottom: 1px solid rgba(127,127,127,0.3); padding: 0.75rem 0; }
  .empty { opacity: 0.6; }
</style>
</head>
<body>
<h1>${name}</h1>
<div id="items" class="empty">Loading…</div>
<!--
  Generated by radar-kit/forge. TODO: replace this placeholder render with the real one —
  never innerHTML on agent-sourced text (titles, summaries, prose all come out of a
  web-search model and are untrusted); build the DOM with createElement/textContent, the
  same idiom every sibling radar's index.html uses. Fetch with { cache: "no-store" } so a
  freshly-written store is seen on the next load, not a stale cached copy.
-->
<script>
  fetch(${JSON.stringify(dataUrl)}, { cache: "no-store" })
    .then((r) => r.json())
    .then((data) => {
      const el = document.getElementById("items")
      const records = ${isServer ? "Array.isArray(data) ? data : []" : "Array.isArray(data && data.records) ? data.records : []"}
      if (records.length === 0) {
        el.textContent = "Nothing yet."
        return
      }
      el.classList.remove("empty")
      el.textContent = ""
      for (const r of records) {
        const div = document.createElement("div")
        div.className = "item"
        div.textContent = JSON.stringify(r)
        el.appendChild(div)
      }
    })
    .catch((err) => {
      document.getElementById("items").textContent = "Failed to load: " + err.message
    })
</script>
</body>
</html>
`
}
