// Generates test/<camel>.test.js — the "tests for key and calibration
// compatibility" FUTURE-PROJECTS.md #9 requires Radar Forge to ship for
// every generated radar. It exercises the REAL radar-kit buildCalibrationBlock
// against a fixture record keyed with this repo's own exported keyOf, so a
// drift between the key a record is written with and the key marks are
// joined by fails loudly here rather than silently in production (an empty
// calibration block every run — the exact failure mode radar-kit's README
// documents keyFields mismatches causing in event-watch/release-radar before
// radar-kit/calibration.js existed).

export function buildTestFile(opts) {
  const { camel, keyFields } = opts
  const sampleRecord = Object.fromEntries(keyFields.map((f, i) => [f, `sample-${f}-${i}`]))
  const sampleRecordJs = JSON.stringify(sampleRecord)

  return `// Generated by radar-kit/forge. Do not delete the calibration-compatibility
// test below when you flesh this file out — it is what FUTURE-PROJECTS.md #9
// calls "tests for key and calibration compatibility," and it is the one
// test in this scaffold that catches a real, previously-seen bug class: a
// record written with one key shape and marks joined with a different one,
// which fails silently (an empty calibration block, forever) rather than
// loudly. See radar-kit/README.md's "Calibration" section for the incident
// history this guards against.

import assert from "node:assert/strict"
import { test } from "node:test"

import { KEY_FIELDS, keyOf } from "../src/${camel}Key.js"
import { buildCalibrationBlock } from "radar-kit/calibration"

test("keyOf is deterministic and normalizes whitespace/case", () => {
  const a = keyOf(${sampleRecordJs})
  const b = keyOf(${sampleRecordJs})
  assert.equal(a, b)
  assert.equal(typeof a, "string")
  assert.ok(a.length > 0)
})

test("KEY_FIELDS is non-empty (a record missing a key field can never be matched to a mark)", () => {
  assert.ok(Array.isArray(KEY_FIELDS) && KEY_FIELDS.length > 0)
})

test("calibration compatibility: buildCalibrationBlock finds a mark keyed with this repo's own keyOf", () => {
  // This is the real join radar-kit's read_calibration tool performs in
  // production: a seen record (this repo's store) joined against a mark
  // (interested.json / ignored.json) by the SAME key function. If a caller
  // anywhere in this repo keys a record or a mark differently than
  // src/${camel}Key.js does, this test fails.
  const record = ${sampleRecordJs}
  const key = keyOf(record)

  const block = buildCalibrationBlock({
    records: [record],
    interested: { [key]: { at: new Date().toISOString(), via: "test" } },
    ignored: {},
    keyFn: keyOf,
    describe: (r) => \`fixture: \${JSON.stringify(r)}\`,
  })

  assert.ok(
    block.includes("fixture:"),
    "buildCalibrationBlock did not find the fixture record via keyOf — the key a record is " +
      "written with and the key a mark is stored under have drifted apart. Compare against " +
      "radar-kit/test/interest-server.test.js's calibration-join tests."
  )
  assert.ok(block.includes("Starred"), "expected the starred section to render for a positive mark")
})

test("calibration compatibility: an unmatched mark (stale key) is dropped, not rendered as noise", () => {
  // The companion case — a mark whose record no longer exists (e.g. it aged
  // out of the store) must not render as a bare, meaningless key. This is
  // buildCalibrationBlock's own contract (see radar-kit/src/calibration.js's
  // joinMarks), asserted here so a future change to this repo's store
  // shape can't silently break it.
  const block = buildCalibrationBlock({
    records: [],
    interested: { "some-stale-key": { at: new Date().toISOString(), via: "test" } },
    ignored: {},
    keyFn: keyOf,
    describe: (r) => \`fixture: \${JSON.stringify(r)}\`,
  })
  assert.ok(
    block.includes("Nothing has been starred or rejected yet"),
    "a mark with no matching record should fall through to the empty-state block, not render as noise"
  )
})
`
}
